# d2 ~/ghq/github.com/badele/nix-homelab/docs/network.d2

direction: right
vars: {
  d2-config: {
    layout-engine: elk
  }
}

title: homelab network {
  shape: text
  near: top-center
  style: {
    font-size: 55
  }
}

internet: internet
internet.shape: cloud

# vlan-adm

mtr254: {
  eth01
  eth02
  eth03
  eth04
}

mtr253: {
  eth02
  eth03
  eth04
  eth05
  eth09
  eth10
}

mtr252: {
  eth02
  eth03
  eth04
  eth05
}

# mtr254
internet -- mtr254.eth01 -- mtr254.bridge: {style.stroke: red}
mtr254.bridge -- mtr254.eth02: tagged VLAN WAR(2) {style.stroke: red}
mtr254.bridge -- mtr254.eth02: tagged VLAN DMZ(32) {style.stroke: orange}
mtr254.bridge -- mtr254.eth02: tagged VLAN ADM(240) {style.stroke: purple}
mtr254.bridge -- mtr254.eth02: tagged VLAN LAN(254) {style.stroke: green}

mtr254.bridge -- mtr254.eth03: tagged VLAN WAR(2) {style.stroke: red}
mtr254.bridge -- mtr254.eth03: tagged VLAN DMZ(32) {style.stroke: orange}
mtr254.bridge -- mtr254.eth03: tagged VLAN ADM(240) {style.stroke: purple}
mtr254.bridge -- mtr254.eth03: tagged VLAN LAN(254) {style.stroke: green}

mtr254.bridge -- mtr254.eth04: LAN {style.stroke: green}
mtr254.eth02 -- mtr253.eth02: Trunk: {style.stroke-width: 8}
mtr254.eth03 -- mtr252.eth02: Trunk: {style.stroke-width: 8}

# mtr253
mtr253.eth02 -- mtr253.router: Trunk: {style.stroke-width: 8}
mtr253.router -- mtr253.eth03: LAN {style.stroke: green}
mtr253.router -- mtr253.eth05: LAN {style.stroke: green}
mtr253.router -- mtr253.eth09: tagged VLAN DMZ(32) {style.stroke: orange}
mtr253.router -- mtr253.eth09: tagged VLAN ADM(240) {style.stroke: purple}
mtr253.eth03 -- laptop: LAN {style.stroke: green}
mtr253.eth05 -- philips hue: LAN {style.stroke: green}
mtr253.eth09 -- hype16: Trunk: {style.stroke-width: 8}

# mtr252
mtr252.eth02 -- mtr252.router: Trunk: {style.stroke-width: 8}
mtr252.router -- mtr252.eth03: LAN {style.stroke: green}
mtr252.router -- mtr252.eth04: LAN {style.stroke: green}
mtr252.router -- mtr252.eth05: LAN {style.stroke: green}
